---
title: "Women in Work Force"
output: html_notebook
---

```{r} 
#Importing Data Set
ss14pusa = read.csv(file.choose(),header=TRUE)  # read csv file
ss14pusb = read.csv(file.choose(),header=TRUE)

#Libraries
require(plyr)
require(dplyr)
```

```{r}
#Importing Data Set in a faster way
library(data.table)
variables=c("SEX","OCCP","WKHP","MAR","WAGP","SCHL","ESP","RAC1P","ST","PAOC","PWGTP")
ss14pusa=fread("C:/Users/user/Desktop/Statistics/3rd semester/ADS/Project1/csv_pus/ss14pusa.csv",head=TRUE,select=variables)
ss14pusb=fread("C:/Users/user/Desktop/Statistics/3rd semester/ADS/Project1/csv_pus/ss14pusb.csv",head=TRUE,select=variables)
```

```{r}
attach(ss14pusa)
names(ss14pusa)
ss14pusa_edit = data.frame(SEX,OCCP,WKHP,MAR,WAGP,SCHL,ESP, RAC1P, ST, PAOC, PWGTP)
detach(ss14pusa)

attach(ss14pusb)
ss14pusb_edit = data.frame(SEX,OCCP,WKHP,MAR,WAGP,SCHL,ESP, RAC1P, ST, PAOC, PWGTP)
detach(ss14pusb)

Data = rbind(ss14pusa_edit,ss14pusb_edit)
colnames(Data) <- c("Gender","Occupation", "Work_hours", "Marriage", "Income", "Education" ,"Parental_Occupation", "Race", "State", "Children", "Weight")


write.csv(Data, file = "Data.csv",row.names=TRUE)
```

```{r}
#Delete income=0/NA rows
row_to_keep=which(Data$Income>0)
Data=Data[row_to_keep,]
```

```{r, echo = FALSE}
#recode OCCP
class(Data$Occupation) <- "numeric"
Data$Occupation <- ifelse(Data$Occupation >= 10 & Data$Occupation <= 430, 1, Data$Occupation)
Data$Occupation <- ifelse(Data$Occupation >= 1005 & Data$Occupation <= 1240, 2, Data$Occupation)
Data$Occupation <- ifelse(Data$Occupation >= 800 & Data$Occupation <= 950, 3, Data$Occupation)
Data$Occupation <- ifelse(Data$Occupation >= 2105 & Data$Occupation <= 2160, 4, Data$Occupation)
Data$Occupation <- ifelse(Data$Occupation >= 3000 & Data$Occupation <= 3540, 5, Data$Occupation)
Data$Occupation <- ifelse(Data$Occupation >= 510 & Data$Occupation <= 740, 6, Data$Occupation)
Data$Occupation <- ifelse(Data$Occupation >= 1300 & Data$Occupation <= 1560, 7, Data$Occupation)
Data$Occupation <- ifelse(Data$Occupation >= 1600 & Data$Occupation <= 1965, 8, Data$Occupation)

Data <- filter(Data, Occupation %in% c(1:8))
Data$Occupation <- as.factor(Data$Occupation)

levels(Data$Occupation) <- c('MGR', 'CMM', 'FIN', 'LGL', 'MED' , 'BUS', 'ENG', 'SCI')

#Recode Region
#https://en.wikipedia.org/wiki/List_of_regions_of_the_United_States#/media/File:Census_Regions_and_Division_of_the_United_States.svg
Data$Region <- recode(Data$State,"c(09,23,25,33,44,59,34,36,42)='Northeast';c(17,18,26,38,55,19,20,27,29,31,38,46)='Mid West'; c(10,12,13,24,37,45,51,11,54,01,21,28,47,05,22,40,48)='South';c(04,08,16,30,32,35,49,50,02,06,15,41,53)='West'))

#Recode Education
Data$Education <- recode(Data$Education,"c(01,02,03,04,05,06,07,08,09,10,11)='~greade8';c(12,13,14,15,16,17,18,19)='grade9~college_nodegree';c(20,21)='associate/bachelor';c(22,23)='master/professional';c(24)='doctor')

```

```{r}
#Recode Education/Gender
library(car)
Data$Education <- recode(Data$Education,"1:11='~grade8';12:19='grade9~college_nodegree';20:21='associate/bachelor';22:23='master/professional';24='doctor'")
```
```{r}
#Recode Gender
Data$Gender <- recode(Data$Gender,"1='Male';2='Female'")
```

```{r}

median_income<-median(Data$Income)
median_income #median income of working men/women=$31000
#below vs.above median percentage for each sex?
Data$Income_median<-ifelse(Data$Income>=median_income,"above","below")
prop.table(table(Data$Income_median,Data$Gender),2)
barplot(prop.table(table(Data$Income_median,Data$Gender),2),legend.text=TRUE)
#women below median >> men below median -> vulnerable women!
```
```{r}
#Can EDUCATION be the factor that makes women vulnerable?
# Education attainments would affect the income
Data$Education=factor(Data$Education,c("~grade8","grade9~college_nodegree","associate/bachelor","master/professional","doctor"))
boxplot(Income~Education, data=Data[,], main=toupper("Income by Educational attainment"), font.main=3, cex.main=1.2, xlab="Educational attainment", ylab="Income", font.lab=1, col="darkgreen")
# but, this effect is significant in women?
#high education group - little difference between sex
```


```{r, echo = FALSE}
#add in weights...example code from previous project:

df1<-svrepdesign(variables=pus_new[,1:13], 
repweights=pus_new[,14:93], type="BRR",combined.weights=TRUE,
weights=pus_new$PWGTP)
summary(df1)
svymean(~ WAGP,df1, na.rm = T)

#If We only want to know the SE and Mean of Statistics Income?

pus_new$FOD1P[pus_new$FOD1P == 3702 | pus_new$FOD1P == 6212 | pus_new$FOD1P == 6202]<-"Statistics"
df<-subset(pus_new, pus_new$FOD1P=="Statistics")
df2<-svrepdesign(variables=df[,1:13], 
repweights=df[,14:93], type="BRR",combined.weights=TRUE,
weights=df$PWGTP)
summary(df2)
svymean(~ WAGP,df2, na.rm = T)
```

```{r, echo = FALSE}

#median wage for each occupation by gender (just to acknowledge that there *is* a gender gap)

Data_sex_occp <- ddply(Data, .(Gender, Occupation), summarise, MEAN = weighted.mean(Income, Weight, na.rm = T))
ggplot(Data_sex_occp, aes(x=Occupation, y=MEAN, fill=factor(Gender))) + 
  geom_bar(stat="identity",position="dodge") + 
  scale_fill_brewer(palette="RdYlGn") +
  labs(fill="") + 
  ylab("Mean Salary ($)") + 
  xlab("Occupations") + 
  ggtitle(paste("Salary Comparison between Men & Women")) + 
  theme(axis.text.x = element_text(angle = 30, hjust = 1), 
        panel.background = element_rect(fill = 'white' )) + 
  theme_grey(base_size = 12)

```

```{r, echo = FALSE}
#subset on women, explore groups of women
Data_women <- filter(Data, Gender == 2)
#Race - Catherine
#Motherhood - 
#Marital Status - Erica (potentially add in region)
#Proportion of graduate degrees in each occupation?
#Region - Vivien

```

```{r, echo = FALSE}

```